name: deploy website
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: debian-unprivileged-runner
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: restore cached node modules
        uses: actions/cache/restore@v4
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/bun.lockb') }}

      - name: install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: bun install

      - name: build
        run: bun run build

      - name: save node modules cache
        uses: actions/cache/save@v4
        id: cache-node-modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/bun.lockb') }}

      - name: deploy
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"
          git remote add main "https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@git.gay/iris/www.git"

          git fetch main
          git checkout -B pages

          if [ ! -d dist ]; then
            echo "dist/ directory does not exist. aborting."
            exit 1
          fi

          find . -maxdepth 1 ! -name . -a ! -name .git -a ! -name .gitignore -a ! -name dist -exec rm -rf {} +
          cp -r dist/* .

          git add .
          git commit -m "deploy docs"
          git push codeberg pages --force
